name: workflow Events
on: [push,pull_request]

jobs:
  single-job:
    runs-on: ubuntu-latest
    steps:
      - name: Display Trigger Name
        run: echo "I've been triggered by ${{ github.event_name }} event"


